import { ClerkProvider } from '@clerk/nextjs';
import { Montserrat } from 'next/font/google';
import Header from '../components/Header'; // Import the Header component
import './globals.css';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header /> {/* Use the Header component here */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
